apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: travelmaster
data:
  # Kafka configuration
  kafka.bootstrap.servers: "kafka-service:9092"
  
  # Redis configuration
  redis.host: "redis-service"
  redis.port: "6379"
  
  # PostgreSQL configuration
  postgres.host: "postgres-service"
  postgres.port: "5432"
  
  # Zipkin configuration
  zipkin.url: "http://zipkin-service:9411"
  
  # Prometheus configuration
  prometheus.url: "http://prometheus-service:9090"
  
  # Environment
  environment: "production"
  
  # Logging level
  logging.level.root: "INFO"
  logging.level.app: "DEBUG"

