apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: travelmaster
data:
  application.yml: |
    server:
      port: 8080
    
    spring:
      application:
        name: gateway-service
      
      cloud:
        gateway:
          routes:
            - id: user-service
              uri: http://user-service:8081
              predicates:
                - Path=/api/auth/**,/api/users/**
            
            - id: trip-service
              uri: http://trip-service:8082
              predicates:
                - Path=/api/trips/**
            
            - id: booking-service
              uri: http://booking-service:8083
              predicates:
                - Path=/api/bookings/**
            
            - id: payment-service
              uri: http://payment-service:8084
              predicates:
                - Path=/api/payments/**
            
            - id: notification-service
              uri: http://notification-service:8085
              predicates:
                - Path=/api/notifications/**
            
            - id: analytics-service
              uri: http://analytics-service:8086
              predicates:
                - Path=/api/analytics/**
          
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      
      data:
        redis:
          host: redis-service
          port: 6379
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      metrics:
        export:
          prometheus:
            enabled: true
    
    logging:
      level:
        root: INFO
        com.travelmaster: DEBUG

