# Staging environment values

replicaCount: 1

image:
  tag: "develop"

ingress:
  hosts:
    - host: staging-api.travelmaster.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: travelmaster-staging-tls
      hosts:
        - staging-api.travelmaster.com

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false

services:
  gateway:
    replicas: 1
  user:
    replicas: 1
  trip:
    replicas: 1
  booking:
    replicas: 1
  payment:
    replicas: 1
  notification:
    replicas: 1
  analytics:
    replicas: 1

