# Поддержите проект TravelMaster Platform
# Ваша поддержка помогает развивать open-source проекты

# GitHub Sponsors
# github: shuldeshoff

# Buy Me a Coffee
# buy_me_a_coffee: shuldeshoff

# Ko-fi
# ko_fi: shuldeshoff

# Patreon
# patreon: shuldeshoff

# Open Collective
# open_collective: travelmaster

# Пользовательские ссылки для поддержки
# custom: ["https://t.me/shuldeshoff", "https://www.paypal.me/shuldeshoff"]

# Раскомментируйте нужные платформы после их настройки
