spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users/**
        
        - id: trip-service
          uri: http://trip-service:8082
          predicates:
            - Path=/api/v1/trips/**
        
        - id: booking-service
          uri: http://booking-service:8083
          predicates:
            - Path=/api/v1/bookings/**
        
        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/api/v1/payments/**
        
        - id: analytics-service
          uri: http://analytics-service:8086
          predicates:
            - Path=/api/v1/analytics/**
  
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}

logging:
  level:
    root: INFO
    com.travelmaster: INFO
    org.springframework.cloud.gateway: INFO

