global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'travelmaster-local'
    environment: 'development'

# Alertmanager configuration (опционально)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Правила для алертов
rule_files:
  # - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Gateway Service
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8080']
        labels:
          service: 'gateway'
          app: 'travelmaster'

  # User Service
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']
        labels:
          service: 'user'
          app: 'travelmaster'

  # Trip Service
  - job_name: 'trip-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['trip-service:8082']
        labels:
          service: 'trip'
          app: 'travelmaster'

  # Booking Service
  - job_name: 'booking-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['booking-service:8083']
        labels:
          service: 'booking'
          app: 'travelmaster'

  # Payment Service
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8084']
        labels:
          service: 'payment'
          app: 'travelmaster'

  # Notification Service
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8085']
        labels:
          service: 'notification'
          app: 'travelmaster'

  # Analytics Service
  - job_name: 'analytics-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['analytics-service:8086']
        labels:
          service: 'analytics'
          app: 'travelmaster'

  # PostgreSQL Exporter (если добавим)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis Exporter (если добавим)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Kafka Exporter (если добавим)
  # - job_name: 'kafka'
  #   static_configs:
  #     - targets: ['kafka-exporter:9308']

